### PR TITLE
Added good animation and CSS to cards

### PR DESCRIPTION
**Pull request by Abhinavcode13**
Updated the our values section of the website.

image

Closes issue number #95

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
@gaurav-verma01 please check the PR
Thanks

**Comment by Gaurav-Verma07** [comment]
@Abhinavcode13 , can you modify this section as in https://www.figma.com/file/OXbrr6UStdn4bHuB5POeRH/sampark?type=design&node-id=0%3A1&t=RCItia46CnzqXFx8-1.
I'm assigning it under `level3`

Thanks

**Comment by Gaurav-Verma07** [comment]
Also make it responsive as well.

**Comment by Abhinavcode13** [comment]
image



hey @Gaurav-Verma07 you want border in the containers or not , let me know does it look fine.

**Comment by Abhinavcode13** [comment]
Issue number 92 contributor has already worked on responsiveness of website @Gaurav-Verma07 so its sorted I guess ;)

**Comment by Gaurav-Verma07** [comment]
keep same dimensions for all boxes and remove the border

**Comment by Abhinavcode13** [comment]
image

Yes removed border and sized the all boxes same @Gaurav-Verma07

**Comment by Abhinavcode13** [comment]
Please check it now @Gaurav-Verma07 
thanks

**Comment by Abhinavcode13** [comment]
image
it looks good to me in mobile too @Gaurav-Verma07 have a look

**Comment by Gaurav-Verma07** [comment]
Yea bro that looks goods.. we can take care of fonts later

**Comment by Gaurav-Verma07** [comment]
Bug- third box has different border-radius than first two.
Increase space between boxes.
You can open a new issue for these changes

**Pull request merged**
