### PR TITLE
feat: add separate blog page

### PR DESCRIPTION
**Pull request by suzy-g38**
Issue No: #91

Added a separate page for all blogs, and connected it with the home page.

Though I have updated the blog content page with the same blog to make this page look more content.
This is the overall look.

image

### CODE REVIEW

**Comment by Gaurav-Verma07** [comment]
I tried re-installing the modules but still it failed
image

**Comment by suzy-g38** [comment]
> I tried re-installing the modules but still it failed image

Yes this happened in my setup also....I thought maybe it was coming just for my setup because the site url was working fine...so I comment out the map part (those caurosal) part then it worked....if it is happening same in your setup then I will look into it.

**Comment by Gaurav-Verma07** [comment]
any luck with it??

**Comment by suzy-g38** [comment]
> any luck with it??

Sorry really forgot about it, give me tomorrow, and I will update you. Sorry.

**Comment by Gaurav-Verma07** [comment]
It's ok. No issues

**Review by suzy-g38 — COMMENTED** [review]
error fixed

**Comment by suzy-g38** [comment]
@Gaurav-Verma07 I have fixed the error, for some reason, the mantine core's version was changed. I think now it will work fine.

**Comment by Gaurav-Verma07** [comment]
Hii, @suzy-g38 please take a look at package.json

**Comment by suzy-g38** [comment]
> Hii, @suzy-g38 please take a look at package.json

I had updated it...is it still not working?

**Comment by suzy-g38** [comment]
> > Hii, @suzy-g38 please take a look at package.json
> 
@Gaurav-Verma07 I had updated it...is it still not working?

**Comment by Gaurav-Verma07** [comment]
@suzy-g38 , the code in package.json seems to be repeated many times, throwing an error

**Pull request merged**
