### PR TITLE
Add logo of website in sign-in page

### PR DESCRIPTION
**Pull request by vk20july**
Screenshot (224)

please review @Gaurav-Verma07 sir
issue: #8

### CODE REVIEW

**Comment by Gaurav-Verma07** [comment]
Bro I meant to place it in this section
image

**Comment by vk20july** [comment]
Oh ok sir i will do it positiviely by tomorrow

**Comment by vk20july** [comment]
> Bro I meant to place it in this section
> image
> 

Means center?

**Comment by Gaurav-Verma07** [comment]
looks good.
thanks

**Comment by vk20july** [comment]
> looks good. thanks

thank you sir,please merge it so that i get points in the leaderboard

**Pull request merged**
