### PR TITLE
made changes in the our values section

### PR DESCRIPTION
**Pull request by shruti8302**
Screenshot (397)

I have also added transition effect on hover so it will scale up as shown in growth section and then slowly turn back to it's original size.

### CODE REVIEW

**Comment by Gaurav-Verma07** [comment]
1. remove `values-container` shadow making it like other sections.
2. remove the horizontal rule
3. boxes are not responsive
4. use `min-width` instead of **max-width** 

please fix these bugs @shruti8302

**Comment by shruti8302** [comment]
> 1. remove `values-container` shadow making it like other sections.
> 2. remove the horizontal rule
> 3. boxes are not responsive
> 4. use `min-width` instead of **max-width**
> 
> please fix these bugs @shruti8302

Sure

**Comment by shruti8302** [comment]
Hey @Gaurav-Verma07 I have removed the horizontal row and values-container shadow as you said but can u please ask someone else to make it responsive. Due to some personal reasons, I currently don't have time to make all those changes. Thanks btw for giving me the opportunity to contribute in your project.

**Comment by Gaurav-Verma07** [comment]
Sure, thanks for your contribution😊

**Pull request merged**
