### PR TITLE
#162 bot added

### LINKED ISSUE #162: Add close old issue bot
### Description

Proposal: Close Old Issue Bot
Description: The Close Old Issue Bot is an automated tool designed to identify and close inactive or resolved issues in a timely manner. It improves issue management efficiency by reducing clutter and ensuring active focus on relevant tasks.
Features:
1. Issue Tracking: Monitors issue activity and identifies those that have remained inactive for a specified period.
2. Automatic Closure: Closes old or resolved issues based on predetermined criteria, promoting a clean and organized issue tracker.
3. Customizable Settings: Allows users to define their own criteria for determining issue activity and closure, adapting to the specific needs of their project.

### Screenshots

_No response_

### Additional information

Assign this to me under gssoc'23 
i will create a pr soon

### PR DESCRIPTION
**Pull request by k-deepak04**
## Related Issue

Closes #162 

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by k-deepak04** [comment]
@Gaurav-Verma07 pr created kindly review and merge 
thanks :)

**Comment by Gaurav-Verma07** [comment]
bro change the old issue open period to 2 weeks

**Comment by k-deepak04** [comment]
@Gaurav-Verma07 Sure bro 
I'm out now 
Will do as soon as i reach home :)

**Comment by k-deepak04** [comment]
@Gaurav-Verma07 updated 
kindly merge this so that i can file another PR :)

**Comment by Gaurav-Verma07** [comment]
the issues will automatically closes or I've to do any configuration?

**Comment by k-deepak04** [comment]
@Gaurav-Verma07 this will automatically close the issue 
please merge it but don't label this pr

**Comment by k-deepak04** [comment]
@Gaurav-Verma07 please add labels , as i have changed the no. of days so i guess we can count this in gssoc, please do the needful

**Pull request merged**
