### PR TITLE
Added feature issue template

### PR DESCRIPTION
**Pull request by Abhinavcode13**
## Related Issue

Closes issue number #100

## Description

Added feature issue template

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
Please check this PR @gaurav-verma01

**Comment by Abhinavcode13** [comment]
Please add the labels @Gaurav-Verma07 as mentioned in issue

**Comment by Abhinavcode13** [comment]
@Gaurav-Verma07 ?

**Comment by Gaurav-Verma07** [comment]
Please check labels now

**Pull request merged**
