### PR TITLE
 Hover effect added on navbar

### PR DESCRIPTION
**Pull request by HimanshuNarware**
##Description
Hover effect was added on the navbar, it will improve the UI of the website.

##issue code
 #40

##Screenshot

### CODE REVIEW

**Comment by kunal-2002** [comment]
I understand what needs to be done here, let me take it up this issue under GSSOC'23. I will make this navbar having responsive UI and hover effect.

**Comment by Gaurav-Verma07** [comment]
@kunal-2002  already in progress

**Comment by Gaurav-Verma07** [comment]
@HimanshuNarware , bro this hover effect doesn't looking good, just keep the bottom-border on hover and animate it from left to right when the user hovers, also remove the box shadow and font-weight

**Comment by HimanshuNarware** [comment]
> @HimanshuNarware , bro this hover effect doesn't looking good, just keep the bottom-border on hover and animate it from left to right when the user hovers, also remove the box shadow and font-weight

ok

**Pull request closed without merging**
